trigger:
- master

jobs:
- job: PyPi_Linux
  pool:
   vmImage: 'ubuntu-latest'

  variables:
  - name: build_num
    value: $(Build.BuildNumber)

  steps:
  - script: npm install
    displayName: npm install
#  - script: npm run compile
#    displayName: build extension
  - script: |
      sudo npm install -g vsce
      date=`date +%Y%m%d%M`
      sed -i -e "s/\"version\".*:.*\"\([0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\)\"/\"version\": \"\1.${date}\"/g" package.json
      vsce package
    displayName: Create VSIX
  - script: |
      if test "$(Build.SourceBranchName)" = "master"; then
         vsce publish -p $(VSCODE_MARKETPLACE_TOKEN)
      fi
    displayName: Publish VSIX
    
